version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-5000}:5000"
    # environment:
    #   - DATA_PATH=/app/data/data.csv
    #   - POSTGRES_HOST=db
    #   - POSTGRES_PORT=5432
    #   - POSTGRES_DB=llm_db
    #   - POSTGRES_USER=llm_user
    #   - POSTGRES_PASSWORD=llm_pass
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5423}:5432"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volume:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    depends_on:
      - postgres
volumes:
  posgres_data:
  grafana_data:
